options:
  email:
    type: string
  domain:
    type: string
  namecheap-api-user:
    type: string
    default:
  namecheap-api-key:
    type: string
    default:
  namecheap-http-timeout:
    type: int
    default: 60
  namecheap-polling-interval:
    type: int
    default: 15
  namecheap-propagation-timeout:
    type: int
    default: 3600
  namecheap-ttl:
    type: int
    default: 120
  namecheap-sandbox:
    type: bool
    default: false